### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by smartynovych**
Please, update symfony/finder version
thanks

### CODE REVIEW

**Comment by Gregwar** [comment]
What is the reason for this?

**Comment by smartynovych** [comment]
image

I can`t update gregwar/captcha to version 1.1.4

**Comment by Gregwar** [comment]
Ok
I might have to retag 
Can you confirm its ok?

**Comment by smartynovych** [comment]
Yes, thanks! this solved the problem, but we have one dependency Gregwar/Captcha-bundle with Gregwar/Captcha that does not allow us to update stable versions. If I manually change to the dev-master, then both packages are installed without problems, so we wating for new release for both packages

**Comment by andreybolonin** [comment]
@Gregwar yes, can you retag?

**Pull request merged**
