### PR TITLE
bugfix division by zero

### PR DESCRIPTION
**Pull request by whyte624**
https://github.com/Gregwar/Captcha/issues/26

### CODE REVIEW

**Comment by Gregwar** [comment]
Actually, this doesn't inform us why zero-length phrases are passed by CaptchaBundle to Captcha
Do you have any use case to reproduce the bug? (ping #26)

**Comment by whyte624** [comment]
I see this error when I visit direct url to generate captcha, e.g. /generate-captcha/gcb_turing?1441975979698

Then in error method here vendor/gregwar/captcha-bundle/Controller/CaptchaController.php:73
$phrase = '';

**Comment by Gregwar** [comment]
OK, Sounds good to me

**Comment by whyte624** [comment]
Isn't it time to prepare a new release?

**Pull request merged**
